#Set the time how long to play in seconds
#10800 = 3:00h
#7200 = 2:00h
#3600 = 1:00h
time: 10800
#Set the number of jokers
joker: 5
#Set if players should be able to move before start of the challange or not
moveable: true